include_recipe "gcc"
include_recipe "git"
include_recipe "icu4c"
include_recipe "memcached"
include_recipe "mysql"
include_recipe "node"
include_recipe "phantomjs"
include_recipe "pow"
include_recipe "python"
include_recipe "qt"
include_recipe "rbenv"
include_recipe "redis"

rbenv_version "1.9.3-p194"
